name: Terraform Plan

on:
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    runs-on: self-hosted
    timeout-minutes: 15
    env:
      TF_VAR_panorama-server: 192.168.1.109
      TF_VAR_device-group: DG1
      TF_VAR_password: ${{ secrets.PANOS_PASSWORD }}
      TF_VAR_username: ${{ secrets.PANOS_USERNAME }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false
