name: Terraform Apply

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    runs-on: [self-hosted, windows, x64]

    env:
      TF_IN_AUTOMATION: true
      TF_VAR_panos_hostname: ${{ secrets.PANOS_HOSTNAME }}
      TF_VAR_panos_password: ${{ secrets.PANOS_PASSWORD }}
      TF_VAR_panos_username: ${{ secrets.PANOS_USERNAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
